services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${AMA_DATABASE_PORT:-5432}:3306
    environment:
      POSTGRES_USER: ${AMA_DATABASE_USER}
      POSTGRES_PASSWORD: ${AMA_DATABASE_PASSWORD}
      POSTGRES_NAME: ${AMA_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local